# Generated by Django 5.2 on 2025-04-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.CharField(max_length=15, unique=True)),
                ('dob', models.DateField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
